# 線形代数 練習問題 メモ

## 問1.1

$3 \times 2$行列

$$
\left(\begin{array}{cc}
7 & 8 \\
9 & 10 \\
11 & 12
\end{array}\right)
$$

の$(2,1)$成分、第2行、第1列をそれぞれ答えよ。

- (2,1)成分→9
- 第2行→$(9, 10)$
- 第1列→$(7, 9, 11)^T$

## 問1.2

3 次の正方行列 A を

$$
A=\left(\begin{array}{lll}
a_{11} & a_{12} & a_{14} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{array}\right)
$$

と表す。

> 1. A の対角成分を答えよ。

対角成分：$(a_{11}, a_{22}, a_{33})$

> A が対角行列、スカラー行列、上三角行列、下三角行列となるとき、A をそ
れぞれ具体的に表せ。

対角行列

$$
A=\left(\begin{array}{lll}
a_{11} & 0 & 0 \\
0 & a_{22} & 0 \\
0 & 0 & a_{33}
\end{array}\right)
$$

スカラー行列

$$
A=\left(\begin{array}{lll}
a_{11} & 0 & 0 \\
0 & a_{11} & 0 \\
0 & 0 & a_{11}
\end{array}\right)
= a_{11} I
$$

上三角


$$
A=\left(\begin{array}{lll}
a_{11} & a_{12} & a_{14} \\
0 & a_{22} & a_{23} \\
0 & 0 & a_{33}
\end{array}\right)
$$

下三角

$$
A=\left(\begin{array}{lll}
a_{11} & 0 & 0 \\
a_{21} & a_{22} & 0 \\
a_{31} & a_{32} & a_{33}
\end{array}\right)
$$


## 問1.3 

> クロネッカーのデルタ δij (i, j = 1, 2, · · · , n) について、i, j = 1, 2, 3 のとき、δij
の値を求めよ。

クロネッカーのデルタは

$$
\delta_{ij} =
\begin{cases}
    1 & (i = j)\\
    0 & (i \neq j)
\end{cases}
$$

なので、

$$
\delta_{11} = \delta_{22} = \delta_{33} = 1\\
\delta_{12} = \delta_{13} = \delta_{21} = \delta_{23} = \delta_{31} = \delta_{32} = 0\\
$$



## 問1.4

> 3 × 2 行列 $
\left(\begin{array}{ll}
5 & 4 \\
3 & 2 \\
1 & 0
\end{array}\right)
$
の転置行列を求めよ。

$$
\left(\begin{array}{ll}
5 & 3 & 1\\
4 & 2 & 0
\end{array}\right)
$$


## 問1.5

> 次の 1、2 の等式が成り立つように a, b, c の値を求めよ。

> 1.
$$
\left(\begin{array}{ll}
a^2+b^2 & a b+b c \\
a b+b c & b^2+c^2
\end{array}\right)=\left(\begin{array}{ll}
1 & 0 \\
0 & 4
\end{array}\right)
$$


※行列を使うとかではないらしい

$$
a^2 + b^2 = 1\\
ab + bc = 0\\
b^2 + c^2 = 4
$$

$ab + bc = 0 \to b(a+c)=0$

より、$b = 0$ or $a + c = 0$の可能性がある


$$
ab = - bc
$$

のため

$a+c=0$について検討する

$$
(a^2 + b^2) - (b^2 + c^2) = 1 - 4\\
\to a^2 - c^2 = -3\\
\to \sqrt{ a^2 - c^2 } = \sqrt{ -3 }\\
\to a - c = \sqrt{ -3 }\\
\to a = \sqrt{ -3 } + c\\
\to a + c = \sqrt{ -3 } + 2c \neq 0\\
$$



よって$b = 0$の可能性のみになるので、

$$
a^2 + b^2 = a^2 = 1 \to a = \pm 1\\
b^2 + c^2 = c^2 = 4 \to c = \pm 2\\
$$

> 2.
$$
\left(\begin{array}{ccc}
a^2+b^2 & 1 & 2 a c \\
1 & 1 & 1 \\
2 c a & 1 & b^2+c^2
\end{array}\right)=\left(\begin{array}{ccc}
1 & 2 b c & 1 \\
2 b c & c^2+a^2 & 2 a b \\
1 & 2 a c & 1
\end{array}\right)
$$


$$
\begin{cases}
\begin{align}
a^2 + b^2 &= 1\\
b^2 + c^2 &= 1\\
c^2 + a^2 &= 1\\
2ab &= 1\\
2ac &= 1\\
2bc &= 1\\
\end{align}
\end{cases}
$$

という連立方程式とする

$$
\begin{align}
(a^2 + b^2) - (b^2 + c^2) &= 1 - 1\\
\to a^2 - c^2 &= 0 \\
\to a^2 = c^2
\\
(a^2 + b^2) - (a^2 + c^2) &= 1 - 1\\
\to b^2 - c^2 &= 0 \\
\to b^2 = c^2
\\
\therefore a^2 = b^2 = c^2
\end{align}
$$


$$
a^2 + b^2 = 1\\
\to 2 a^2 = 1\\
\to a^2 = \frac{1}{2}\\
$$

両辺に平方根をかけて

$$
\sqrt{a^2} = \sqrt{\frac{1}{2}}
$$

$a$の符号はわからないので

$$
|a| = \sqrt{\frac{1}{2}}
$$

平方根を単純化する

$$
|a| = \frac{1}{\sqrt{2}}
$$

有理化する

$$
|a| = \frac{1}{\sqrt{2}} \times \frac{ \sqrt{2} }{ \sqrt{2} } = \frac{ \sqrt{2} }{2}
$$

したがって

$$
a = \pm \frac{ \sqrt{2} }{2}
$$






同様に

$$
a^2  = b^2 = c^2 = \frac{1}{2}\\
a = b = c = \pm \frac{\sqrt{2} }{2}\\
$$

## 問1.6 

> A を (i, j) 成分が次の 1～4 により定められる 3 次の正方行列とする。A をそれぞれ具体的に表せ。

1. $a_{i j}=i+j$
2. $a_{i j}=i j$
3. $a_{i j}=(-1)^{i+j}$
4. $a_{i j}=(-1)^{i j}$


$$
A=\left(\begin{array}{lll}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{array}\right)
$$

なので

> 1. $a_{i j}=i+j$

$$
\begin{pmatrix}
2 & 3 & 4\\
3 & 4 & 5\\
4 & 5 & 6\\
\end{pmatrix}
$$

> 2. $a_{i j}=i j$

$$
\begin{pmatrix}
1 & 2 & 3\\
2 & 4 & 6\\
3 & 6 & 9\\
\end{pmatrix}
$$

> 3. $a_{i j}=(-1)^{i+j}$

$$
\begin{pmatrix}
1 & -1 & 1\\
-1 & 1 & -1\\
1 & -1 & 1\\
\end{pmatrix}
$$

> 4. $a_{i j}=(-1)^{i j}$

$$
\begin{pmatrix}
-1 & 1 & -1\\
1 & 1 & 1\\
-1 & 1 & -1\\
\end{pmatrix}
$$

## 問1.7

> 1. 対称行列の定義を書け

転置してももとの行列と変わらない正方行列

$$
A = A^T
$$

> 2. 次の（ア）、（イ）の行列が対象行列となるように a の値を求めよ。
>
> $$\text { (ア) }\left(\begin{array}{cc}
1 & a \\
a^2 & a^3
\end{array}\right) \quad \text { (イ) }\left(\begin{array}{ccc}
1 & a & a^2 \\
a^3 & a^4 & a^5 \\
a^6 & a^7 & a^8
\end{array}\right)
$$

（ア）
$$
\left(\begin{array}{cc}
1 & a \\
a^2 & a^3
\end{array}\right)
= \left(\begin{array}{cc}
1 & a^2 \\
a & a^3
\end{array}\right)
$$

で

$$
a^2 = a\\
\to a(a-1) = 0\\
$$

$a=0$あるいは$a-1=0 \to a=1$

$$
\therefore a=0, 1
$$

（イ）

$$
a^3 = a\\
a^6 = a^2\\
a^7 = a^5
$$

なので

$$
a^3 -a = 0\\
\to a (a^2 - 1) = 0\\
\to a = 0, 1, -1
$$


## 問1.8

> 次の 1～3 の行列の (i, j) 成分をクロネッカーのデルタを用いて表せ。


> 1. $\left(\begin{array}{lll}
1 & 0 & 0 \\
0 & 2 & 0 \\
0 & 0 & 3
\end{array}\right)$


行列の$(i,j)$要素を$a_{ij}$と表すことにすると

$$
a_{ij} = i \times \delta_{ij}
$$


> 2. $\left(\begin{array}{lll}
0 & 1 & 0 \\
0 & 0 & 1 \\
0 & 0 & 0
\end{array}\right)$

$$
a_{ij} = \delta_{(i+1), j}
$$

> 3. $\left(\begin{array}{lll}
0 & 0 & 0 \\
1 & 0 & 0 \\
0 & 1 & 0
\end{array}\right)$

$$
a_{ij} = \delta_{i-1, j}
$$

---

## 2.1

> $$
3\left(\begin{array}{ll}
4 & 7 \\
5 & 8 \\
6 & 9
\end{array}\right)+\left(\begin{array}{ll}
0 & 1 \\
1 & 2 \\
2 & 0
\end{array}\right)
$$


$$
\left(\begin{array}{ll}
12 & 21 \\
15 & 24 \\
18 & 27
\end{array}\right)
+\left(\begin{array}{ll}
0 & 1 \\
1 & 2 \\
2 & 0
\end{array}\right)
=\left(\begin{array}{ll}
12 & 22 \\
16 & 26 \\
20 & 27
\end{array}\right)
$$

## 2.2

> 1. $$
\left(\begin{array}{lll}
3 & 4 & 5
\end{array}\right)\left(\begin{array}{ll}
0 & 1 \\
1 & 2 \\
2 & 0
\end{array}\right)
$$

$$
(3\cdot 0 + 4 \cdot 1 + 5 \cdot 2, \hspace{1em} 3\cdot 1 + 4 \cdot 2 + 0)\\
= (14, 11)
$$

> 2. $$
\left(\begin{array}{l}
3 \\
4
\end{array}\right)\left(\begin{array}{ll}
1 & 2
\end{array}\right)
$$

$$
\left(\begin{array}{l}
a_1 \\
a_2
\end{array}\right)
\left(\begin{array}{ll}
b_1 & b_2
\end{array}\right)
= \begin{pmatrix}
a_1 b_1 & a_1 b_2\\
a_2 b_1 & a_2 b_2\\
\end{pmatrix}
$$

なので

$$
\left(\begin{array}{l}
3 \\
4
\end{array}\right)\left(\begin{array}{ll}
1 & 2
\end{array}\right)
= \begin{pmatrix}
3\cdot 1 & 3 \cdot 2\\
4\cdot 1 & 4 \cdot 2\\
\end{pmatrix}
= \begin{pmatrix}
3 & 6\\
4 & 8\\
\end{pmatrix}
$$

In [6]:
import numpy as np
a = np.array([3,4])
b = np.array([1,2])
np.outer(a,b)

array([[3, 6],
       [4, 8]])

> 2. $$
\left(\begin{array}{ll}
7 & 8
\end{array}\right)\left(\begin{array}{l}
5 \\
6
\end{array}\right)
$$

$$
7\cdot 5 + 8 \cdot 6 = 35 + 48 = 83
$$

## 2.3

> 正方行列$A=\left(\begin{array}{lll}
0 & a & b \\
0 & 0 & c \\
0 & 0 & 0
\end{array}\right)$はべき零行列であることを示せ。

冪零行列は、任意の整数$k$で冪乗して零（零行列）となる正方行列

$$
A^k = O
$$



Aは$k=2$のときは冪零ではないが、$k \geq 3$で冪零

In [22]:
import numpy as np
A = np.array([
    [0, 1, 2],
    [0, 0, 3],
    [0, 0, 0]
])

A @ A

array([[0, 0, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [23]:
A @ A @ A

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## 2.4

> 次の問いに応えよ。
> 
> 1. 2 つの行列が可換であることの定義を書け。

2つの行列$A, B$について

$$
AB = BA
$$

が成り立つこと


> 2. 2 つの行列
> $\left(\begin{array}{cc}
1 & a \\
0 & a^2
\end{array}\right),\left(\begin{array}{cc}
a^2 & a \\
0 & 1
\end{array}\right)$
> が可換となるように a の値を求めよ。


$$
\begin{pmatrix}
1 & a \\
0 & a^2
\end{pmatrix}
\begin{pmatrix}
a^2 & a \\
0 & 1
\end{pmatrix}
= 
\begin{pmatrix}
a^2 & a \\
0 & 1
\end{pmatrix}
\begin{pmatrix}
1 & a \\
0 & a^2
\end{pmatrix}
$$

を満たす、つまり

$$
\begin{pmatrix}
a^2 & 2a \\
0 & a^2
\end{pmatrix}
= 
\begin{pmatrix}
a^2 & 2a^3 \\
0 & a^2
\end{pmatrix}
$$

よって

$$
2a = 2a^3
$$

を解けばよい。

$$
\begin{align}
&2a = 2a^3\\
&\to a = a^3\\
&\to a - a^3 = 0\\
&\to a(a^2 - 1) = 0\\
&\end{align}
$$

よって$a=0$か$a^2 - 1 = 0$であり

$a^2 - 1 = 0$が成り立つのは$a=-1, 1$のときなので

$$
a = -1, 0, 1
$$
となる

In [31]:
# 検算
from sympy import Symbol, Matrix
a = Symbol('a')
A = Matrix([
    [1, a],
    [0, a**2],
])
B = Matrix([
    [a**2, a],
    [0, 1],
])

A @ B

Matrix([
[a**2,  2*a],
[   0, a**2]])

In [38]:
# 検算
import numpy as np

for a in (0, -1, 1):
    A = np.array([
        [1, a],
        [0, a**2]
    ])
    B = np.array([
        [a**2, a],
        [0, 1],
    ])
    assert (A @ B == B @ A).all()

## 2.5

> n 次の正方行列 A, B に対して、$[A, B] = AB − BA$ とおき、これを A と B の交換子積という。
> 交換子積に関して、次の 1～3 が成り立つことを示せ。ただし、A, B, C はすべて n 次の正方行列で、O は n 次の零行列である。

> 1. $[A, B] = −[B, A]$ （交代性または反対称性）


$$
[A, B] = AB - BA
$$

は順番を入れ替えれば

$$
- BA + AB
= - (BA - AB)
= -[B, A]
$$



In [60]:
# 例えば n=2 のとき
from sympy import symbols, Matrix

a11, a12, a21, a22 = symbols("a_11, a_12, a_21, a_22")
b11, b12, b21, b22 = symbols("b_11, b_12, b_21, b_22")

A = Matrix([
    [a11, a12],
    [a21, a22]
])
B = Matrix([
    [b11, b12],
    [b21, b22]
])

(A @ B - B @ A) == (- 1 * (B @ A - A @ B))

True

> 2. $[A, A] = O$

$$
[A, A] = AA - AA = O
$$

> 3. $[[A, B], C] + [[B, C], A] + [[C, A], B] = O$（ヤコビの恒等式）

$$
[[A, B], C] + [[B, C], A] + [[C, A], B]
$$

を展開すると

$$
\begin{align}
  (AB - BA) C &- C (AB - BA)\\
+ (BC - CB) A &- A (BC - CB)\\
+ (CA - AC) B &- B (CA - AC)
\\
= ABC - BAC &- CAB + CBA\\
+ BCA - CBA &- ABC + ACB\\
+ CAB - ACB &- BCA + BAC
\end{align}
$$


$$
= (ABC - ABC)\\
+ (BAC - BAC)\\
+ (CAB - CAB)\\
+ (CBA - CBA)\\
+ (BCA - BCA)\\
+ (ACB - ACB)\\
= 0
$$

## 2.6

> 2 次の正方行列
> $A=\left(\begin{array}{ll}
a & b \\
c & d
\end{array}\right)$
> に対して、ケイリー-ハミルトンの定理
>
> $A^2-(a+d) A+(a d-b c) E$
>
> が成り立つことを示せ。（E は対角要素が 1 の単位行列である）


$$
A^2-(a+d) A+(a d-b c) E = O
$$

ということ?


$$
\begin{align}
&A^2-(a+d) A+(a d-b c) E
\\
&=
\begin{pmatrix}
a & b \\
c & d
\end{pmatrix}
\begin{pmatrix}
a & b \\
c & d
\end{pmatrix}
- a \begin{pmatrix}
a & b \\
c & d
\end{pmatrix}
- d \begin{pmatrix}
a & b \\
c & d
\end{pmatrix}
+(a d-b c) E
\\
&= \begin{pmatrix}
a^2 + bc & ab + bd\\
ac + cd & bc + d^2
\end{pmatrix}
- \begin{pmatrix}
a^2 & ab \\
ac & ad
\end{pmatrix}
- \begin{pmatrix}
ad & bd \\
cd & d^2
\end{pmatrix}
+(a d-b c) E
\\
&= \begin{pmatrix}
bc & bd\\
cd & bc + d^2 - ad
\end{pmatrix}
- \begin{pmatrix}
ad & bd \\
cd & d^2
\end{pmatrix}
+(a d-b c) E
\\
&= \begin{pmatrix}
bc - ad & 0\\
0 & bc - ad
\end{pmatrix}
+(a d-b c) E
\\
&= \begin{pmatrix}
0 & 0\\
0 & 0
\end{pmatrix}
\end{align}
$$


## 2.7

> 次の問いに答えよ。

> 1. 対称行列の定義を書け。

$$
A^T = A
$$

が成り立つこと

> 2. 交代行列の定義を書け。

転置行列が元の行列の−1倍になる、つまり

$$
A^T = -A
$$

が成り立つこと

> 3. 任意の正方行列は対称行列と交代行列の和で一意的に表されることを、次の（ア）、（イ）の手順で示せ。
>
> （ア）正方行列 A が対象行列 X と交代行列 Y の和で、
> $$
A = X + Y \tag{2.1}
$$
> と表されると仮定する。
> このとき、式 2.1 の両辺の転置を取ることにより、
> $$
A^T = X − Y \tag{2.2}
$$
> が成り立つ。
>
> 式 2.1 と式 2.2 を連立させることにより、X, Y を A および $A^T$ を用いて表せ。

$$
\begin{array}{rr}
        & A = X + Y\\
+\big{)}& A^T = X - Y\\
\hline
& A + A^T = 2 X\\
& \to X = \frac{1}{2} (A + A^T)
\end{array}
$$


$$
\begin{array}{rr}
        & A = X + Y\\
-\big{)}& A^T = X - Y\\
\hline
& A - A^T = 2 Y\\
& \to Y = \frac{1}{2} (A - A^T)
\end{array}
$$

> （イ） （ア）で $A$ および $A^T$ を用いて表した X, Y は、実際にそれぞれ対称行列、交代行列であることを示せ。

Xは対称行列

$$
X^T = \frac{1}{2} (A+A^T)^T = \frac{1}{2} (A^T + A) = X
$$

Yは交代行列

$$
\begin{align}
Y^T
&= \frac{1}{2} (A - A^T)^T\\
&= \frac{1}{2} (A^T - A)\\
&= -\frac{1}{2} (A + A^T)\\
&= -Y
\end{align}
$$