# 練習問題 メモ 3

## 3.1

> $A$ を $k \times l$ 行列、 $B$ を $k \times n$ 行列、 $C$ を $m \times n$ 行列とする。分割された $(k+m) \times(l+n)$行列に対する次の計算をせよ。
> $
\left(\begin{array}{cc}
A & B \\
O_{m, l} & C
\end{array}\right)+\left(\begin{array}{cc}
A & -B \\
O_{m, l} & -2 C
\end{array}\right)
$

$$
\left(\begin{array}{cc}
A & B \\
O_{m, l} & C
\end{array}\right)
+
\left(\begin{array}{cc}
A & -B \\
O_{m, l} & -2 C
\end{array}\right)
=
\left(\begin{array}{cc}
A+A & B-B \\
O_{m, l}-O_{m, l} & C-2 C
\end{array}\right)
=
\left(\begin{array}{cc}
2A & O_{k,n} \\
O_{m, l} & -C
\end{array}\right)
$$

## 3.2

> $A$ を $m \times n$ 行列とする。分割された $(m+n)$ 次の正方行列 $\left(\begin{array}{cc}E_m & A \\ O_{n, m} & E_n\end{array}\right)$の3乗を計算せよ。

$$
\left(\begin{array}{cc}E_m & A \\ O_{n, m} & E_n\end{array}\right)^3
= \left(\begin{array}{cc}
    E_m^3 & 3A \\
    O_{n, m} & E_n^3
\end{array}\right)
= \left(\begin{array}{cc}
    E_m & 3A \\
    O_{n, m} & E_n
\end{array}\right)
$$

## 3.3

> 4次の正方行列 $I, J, K$を
> $
I=\left(\begin{array}{cccc}
0 & -1 & 0 & 0 \\
1 & 0 & 0 & 0 \\
0 & 0 & 0 & -1 \\
0 & 0 & 1 & 0
\end{array}\right), J=\left(\begin{array}{cccc}
0 & 0 & -1 & 0 \\
0 & 0 & 0 & 1 \\
1 & 0 & 0 & 0 \\
0 & -1 & 0 & 0
\end{array}\right), K=\left(\begin{array}{cccc}
0 & 0 & 0 & -1 \\
0 & 0 & -1 & 0 \\
0 & 1 & 0 & 0 \\
1 & 0 & 0 & 0
\end{array}\right)
$
> により定める。 $I, J, K$ を 2 次の正方行列を用いて分割することにより、積 $I^2, J^2$, $K^2, I J, J I, J K, K J, K I, I K$ を計算せよ。

> $I^2$

$$
I =
\begin{pmatrix}
I_s & O\\
O & I_s
\end{pmatrix}
$$

とするとブロック行列の性質により

$$
I^2 =
\begin{pmatrix}
I_s^2 & O\\
O & I_s^2
\end{pmatrix}
$$

であり、

$$
I_s^2 = 
\begin{pmatrix}
0 & -1\\
1 & 0
\end{pmatrix}
\begin{pmatrix}
0 & -1\\
1 & 0
\end{pmatrix}
=
\begin{pmatrix}
-1 & 0\\
0 & -1
\end{pmatrix}
$$

なので

$$
I^2 =
\begin{pmatrix}
-1 & 0 & 0 & 0 \\
0 & -1 & 0 & 0 \\
0 & 0 & -1 & 0 \\
0 & 0 & 0 & -1
\end{pmatrix}
$$


In [5]:
import numpy as np
I = np.array([
    [0, -1, 0, 0],
    [1, 0, 0, 0],
    [0, 0, 0, -1],
    [0, 0, 1, 0]
])

I @ I

array([[-1,  0,  0,  0],
       [ 0, -1,  0,  0],
       [ 0,  0, -1,  0],
       [ 0,  0,  0, -1]])

> $J^2$

$$
J =
\begin{pmatrix}
O & J_1 \\
J_2 & O
\end{pmatrix}
$$

とすると

$$
J^2 =
\begin{pmatrix}
J_1 J_2 & O\\
O & J_1 J_2
\end{pmatrix}
$$

$$
J_1 J_2
=
\begin{pmatrix}
-1 & 0 \\
0 & 1
\end{pmatrix}
\begin{pmatrix}
1 & 0 \\
0 & -1
\end{pmatrix}
=
\begin{pmatrix}
-1 & 0 \\
0 & -1
\end{pmatrix}
$$


$$
J_2 J_1
=
\begin{pmatrix}
1 & 0 \\
0 & -1
\end{pmatrix}
\begin{pmatrix}
-1 & 0 \\
0 & 1
\end{pmatrix}
=
\begin{pmatrix}
-1 & 0 \\
0 & -1
\end{pmatrix}
$$

$$
J^2 =
\begin{pmatrix}
-1 & 0 & 0 & 0 \\
0 & -1 & 0 & 0 \\
0 & 0 & -1 & 0 \\
0 & 0 & 0 & -1
\end{pmatrix}
$$


In [6]:
import numpy as np
J = np.array([
    [0, 0, -1, 0],
    [0, 0, 0, 1],
    [1, 0, 0, 0],
    [0, -1, 0, 0]
])

J @ J

array([[-1,  0,  0,  0],
       [ 0, -1,  0,  0],
       [ 0,  0, -1,  0],
       [ 0,  0,  0, -1]])

> $K^2$

$$
K =
\begin{pmatrix}
O & K_1\\
K_2 & O
\end{pmatrix}
$$

とすると

$$
K^2 =
\begin{pmatrix}
K_1 K_2 & O\\
O & K_2 K_1\\
\end{pmatrix}
$$


$$
K_1 K_2
=
\begin{pmatrix}
0 & -1 \\
-1 & 0
\end{pmatrix}
\begin{pmatrix}
0 & 1 \\
1 & 0
\end{pmatrix}
=
\begin{pmatrix}
-1 & 0 \\
0 & -1
\end{pmatrix}
$$

$$
K_2 K_1
=
\begin{pmatrix}
0 & 1 \\
1 & 0
\end{pmatrix}
\begin{pmatrix}
0 & -1 \\
-1 & 0
\end{pmatrix}
=
\begin{pmatrix}
-1 & 0 \\
0 & -1
\end{pmatrix}
$$

$$
K^2 = 
\begin{pmatrix}
-1 & 0 & 0 & 0 \\
0 & -1 & 0 & 0 \\
0 & 0 & -1 & 0 \\
0 & 0 & 0 & -1
\end{pmatrix}
$$


In [7]:
import numpy as np
K = np.array([
    [0, 0, 0, -1],
    [0, 0, -1, 0],
    [0, 1, 0, 0],
    [1, 0, 0, 0]
])

K @ K

array([[-1,  0,  0,  0],
       [ 0, -1,  0,  0],
       [ 0,  0, -1,  0],
       [ 0,  0,  0, -1]])

> $IJ$

$$
IJ
= \begin{pmatrix}
I_s & O\\
O & I_s
\end{pmatrix}
\begin{pmatrix}
O & J_1 \\
J_2 & O
\end{pmatrix}
= \begin{pmatrix}
O & I_s J_1 \\
I_s J_2 & O
\end{pmatrix}
$$

$$
I_s J_1 = 
\begin{pmatrix}
0 & -1 \\
1 & 0
\end{pmatrix}
\begin{pmatrix}
-1 & 0 \\
0 & 1
\end{pmatrix}
=
\begin{pmatrix}
0 & -1 \\
-1 & 0
\end{pmatrix}
$$

$$
I_s J_2 = 
\begin{pmatrix}
0 & -1 \\
1 & 0
\end{pmatrix}
\begin{pmatrix}
1 & 0 \\
0 & -1
\end{pmatrix}
=
\begin{pmatrix}
0 & 1 \\
1 & 0
\end{pmatrix}
$$

$$
IJ = \begin{pmatrix}
0 & 0 & 0 & -1 \\
0 & 0 & -1 & 0 \\
0 & 1 & 0 & 0 \\
1 & 0 & 0 & 0
\end{pmatrix}
$$

In [8]:
I @ J

array([[ 0,  0,  0, -1],
       [ 0,  0, -1,  0],
       [ 0,  1,  0,  0],
       [ 1,  0,  0,  0]])

> $J I$

$$
JI
=
\begin{pmatrix}
O & J_1 \\
J_2 & O
\end{pmatrix}
\begin{pmatrix}
I_s & O\\
O & I_s
\end{pmatrix}
= \begin{pmatrix}
O & J_1 I_s\\
J_2 I_s & O
\end{pmatrix}
$$



$$
J_1 I_s = 
\begin{pmatrix}
-1 & 0 \\
0 & 1
\end{pmatrix}
\begin{pmatrix}
0 & -1 \\
1 & 0
\end{pmatrix}
=
\begin{pmatrix}
0 & 1 \\
1 & 0
\end{pmatrix}
$$

$$
J_2 I_s = 
\begin{pmatrix}
1 & 0 \\
0 & -1
\end{pmatrix}
\begin{pmatrix}
0 & -1 \\
1 & 0
\end{pmatrix}
=
\begin{pmatrix}
0 & -1 \\
-1 & 0
\end{pmatrix}
$$


$$
JI =
\begin{pmatrix}
0 & 0 & 0 & 1 \\
0 & 0 & 1 & 0 \\
0 & -1 & 0 & 0 \\
-1 & 0 & 0 & 0
\end{pmatrix}
$$

In [9]:
J @ I

array([[ 0,  0,  0,  1],
       [ 0,  0,  1,  0],
       [ 0, -1,  0,  0],
       [-1,  0,  0,  0]])

> $J K$

$$
J K =
\begin{pmatrix}
O & J_1 \\
J_2 & O
\end{pmatrix}
\begin{pmatrix}
O & K_1\\
K_2 & O
\end{pmatrix}
=
\begin{pmatrix}
J_1 K_2 & O\\
O & J_2 K_1
\end{pmatrix}
$$


$$
J_1 K_2 =
\begin{pmatrix}
-1 & 0\\
0 & 1
\end{pmatrix}
\begin{pmatrix}
0 & 1\\
1 & 0
\end{pmatrix}
= 
\begin{pmatrix}
0 & -1\\
1 & 0
\end{pmatrix}
$$


$$
J_2 K_1 =
\begin{pmatrix}
1 & 0\\
0 & -1
\end{pmatrix}
\begin{pmatrix}
0 & -1\\
-1 & 0
\end{pmatrix}
=
\begin{pmatrix}
0 & -1\\
1 & 0
\end{pmatrix}
$$

$$
JK =
\begin{pmatrix}
0 & -1 & 0 & 0 \\
1 & 0 & 0 & 0 \\
0 & 0 & 0 & -1 \\
0 & 0 & 1 & 0
\end{pmatrix}
$$

In [10]:
J @ K

array([[ 0, -1,  0,  0],
       [ 1,  0,  0,  0],
       [ 0,  0,  0, -1],
       [ 0,  0,  1,  0]])

> $K J$

$$
K J =
\begin{pmatrix}
O & K_1\\
K_2 & O
\end{pmatrix}
\begin{pmatrix}
O & J_1 \\
J_2 & O
\end{pmatrix}
=
\begin{pmatrix}
K_1 J_2 & O\\
O & K_2 J_1
\end{pmatrix}
$$


$$
K_2 J_1 =
\begin{pmatrix}
0 & 1\\
1 & 0
\end{pmatrix}
\begin{pmatrix}
-1 & 0\\
0 & 1
\end{pmatrix}
= 
\begin{pmatrix}
0 & 1\\
-1 & 0\\
\end{pmatrix}
$$


$$
K_1 J_2 =
\begin{pmatrix}
0 & -1\\
-1 & 0
\end{pmatrix}
\begin{pmatrix}
1 & 0\\
0 & -1
\end{pmatrix}
=
\begin{pmatrix}
0 & 1\\
-1 & 0
\end{pmatrix}
$$

$$
KJ =
\begin{pmatrix}
0 & 1 & 0 & 0 \\
-1 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 \\
0 & 0 & -1 & 0
\end{pmatrix}
$$

In [11]:
K @ J

array([[ 0,  1,  0,  0],
       [-1,  0,  0,  0],
       [ 0,  0,  0,  1],
       [ 0,  0, -1,  0]])

> $K I$

$$
K I =
\begin{pmatrix}
O & K_1\\
K_2 & O
\end{pmatrix}
\begin{pmatrix}
I_s & O \\
O & I_s
\end{pmatrix}
=
\begin{pmatrix}
O & K_1 I_s\\
K_2 I_s & O
\end{pmatrix}
$$

$$
K_1 I_s =
\begin{pmatrix}
0 & -1\\
-1 & 0
\end{pmatrix}
\begin{pmatrix}
0 & -1\\
1 & 0
\end{pmatrix}
=
\begin{pmatrix}
-1 & 0\\
0 & 1
\end{pmatrix}
$$

$$
K_2 I_s =
\begin{pmatrix}
0 & 1\\
1 & 0
\end{pmatrix}
\begin{pmatrix}
0 & -1\\
1 & 0
\end{pmatrix}
= 
\begin{pmatrix}
1 & 0\\
0 & -1\\
\end{pmatrix}
$$

$$
KI =
\begin{pmatrix}
0 & 0 & -1 & 0 \\
0 & 0 & 0 & 1 \\
1 & 0 & 0 & 0 \\
0 & -1 & 0 & 0
\end{pmatrix}
$$

In [12]:
K @ I

array([[ 0,  0, -1,  0],
       [ 0,  0,  0,  1],
       [ 1,  0,  0,  0],
       [ 0, -1,  0,  0]])

> $I K$

$$
I K =
\begin{pmatrix}
I_s & O \\
O & I_s
\end{pmatrix}
\begin{pmatrix}
O & K_1\\
K_2 & O
\end{pmatrix}
=
\begin{pmatrix}
O & I_s K_1\\
I_s K_2 & O
\end{pmatrix}
$$

$$
I_s K_1 =
\begin{pmatrix}
0 & -1\\
1 & 0
\end{pmatrix}
\begin{pmatrix}
0 & -1\\
-1 & 0
\end{pmatrix}
=
\begin{pmatrix}
1 & 0 \\
0 & -1
\end{pmatrix}
$$

$$
I_s K_2 =
\begin{pmatrix}
0 & -1\\
1 & 0
\end{pmatrix}
\begin{pmatrix}
0 & 1\\
1 & 0
\end{pmatrix}
= 
\begin{pmatrix}
-1 & 0\\
0 & 1
\end{pmatrix}
$$

$$
IK =
\begin{pmatrix}
0 & 0 & 1 & 0 \\
0 & 0 & 0 & -1 \\
-1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0
\end{pmatrix}
$$

In [13]:
I @ K

array([[ 0,  0,  1,  0],
       [ 0,  0,  0, -1],
       [-1,  0,  0,  0],
       [ 0,  1,  0,  0]])

## 3.4

> $A_{12}, A_{13}, A_{22}, A_{23}, A_{33}, B_{11}, B_{12}, B_{13}, B_{23}, B_{33}, C_{11}, C_{12}, C_{13}, C_{22}, C_{23}$ を$n$次の正方行列、$O$を$n$次の零行列とする。次の計算をせよ。
> $
\left(\begin{array}{ccc}
O & A_{12} & A_{13} \\
O & A_{22} & A_{23} \\
O & O & A_{33}
\end{array}\right)\left(\begin{array}{ccc}
B_{11} & B_{12} & B_{13} \\
O & O & B_{23} \\
O & O & B_{33}
\end{array}\right)\left(\begin{array}{ccc}
C_{11} & C_{12} & C_{13} \\
O & C_{22} & C_{23} \\
O & O & O
\end{array}\right)
$

$$
\begin{pmatrix}
O & A_{12} & A_{13} \\
O & A_{22} & A_{23} \\
O & O & A_{33}
\end{pmatrix}
\begin{pmatrix}
B_{11} & B_{12} & B_{13} \\
O & O & B_{23} \\
O & O & B_{33}
\end{pmatrix}
=
\begin{pmatrix}
O & O & A_{12} B_{23} + A_{13} B_{33}\\
O & O & A_{22} B_{23} + A_{23} B_{33}\\
O & O & A_{33} B_{33}
\end{pmatrix}
$$


$$
\begin{pmatrix}
O & O & A_{12} B_{23} + A_{13} B_{33}\\
O & O & A_{22} B_{23} + A_{23} B_{33}\\
O & O & A_{33} B_{33}
\end{pmatrix}
\begin{pmatrix}
C_{11} & C_{12} & C_{13} \\
O & C_{22} & C_{23} \\
O & O & O
\end{pmatrix}
$$

$$
\begin{pmatrix}
O & O & A_{12} B_{23} + A_{13} B_{33}\\
O & O & A_{22} B_{23} + A_{23} B_{33}\\
O & O & A_{33} B_{33}
\end{pmatrix}
\begin{pmatrix}
C_{11} & C_{12} & C_{13} \\
O & C_{22} & C_{23} \\
O & O & O
\end{pmatrix}
=
\begin{pmatrix}
O & O & O\\
O & O & O\\
O & O & O
\end{pmatrix}
= O
$$

In [23]:
# 検算
from sympy import symbols, Matrix
A_12, A_13, A_22, A_23, A_33 = symbols("A_12, A_13, A_22, A_23, A_33")
B_11, B_12, B_13, B_23, B_33 = symbols("B_11, B_12, B_13, B_23, B_33")
C_11, C_12, C_13, C_22, C_23 = symbols("C_11, C_12, C_13, C_22, C_23")

A = Matrix([
    [0, A_12, A_13],
    [0, A_22, A_23],
    [0, 0, A_33]
])


B = Matrix([
    [B_11, B_12, B_13],
    [0, 0, B_23],
    [0, 0, B_33]
])

C = Matrix([
    [C_11, C_12, C_13],
    [0, C_22, C_23],
    [0, 0, 0]
])

In [21]:
A @ B

Matrix([
[0, 0, A_12*B_23 + A_13*B_33],
[0, 0, A_22*B_23 + A_23*B_33],
[0, 0,             A_33*B_33]])

In [22]:
A @ B @ C

Matrix([
[0, 0, 0],
[0, 0, 0],
[0, 0, 0]])