# 練習問題 メモ 4

## 4.1

> 次の１～３の行列の階数標準形および階数(rank)を求めよ

### 1.

> 1. $\left(\begin{array}{ll}1 & 2 \\ 3 & 4 \\ 5 & 6\end{array}\right)$


行ベクトルを

$$
\begin{pmatrix}
a_1 \\
a_2 \\
a_3
\end{pmatrix}
$$

とする

1. $a_2' = a_2 + (-2) \times a_1$

In [108]:
import numpy as np
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
])

In [109]:
# 1行目を-2倍して2行目に加える
A[1, :] += A[0, :] * (-2)
A

array([[1, 2],
       [1, 0],
       [5, 6]])

In [110]:
# 1行目を-3倍して3行目に加える
A[2, :] += A[0, :] * (-3)
A

array([[1, 2],
       [1, 0],
       [2, 0]])

In [111]:
# 3行目を(1/2)倍する
A[2, :] = (1 / 2) * A[2, :]
A

array([[1, 2],
       [1, 0],
       [1, 0]])

In [112]:
# 2行目を-1倍して3行目に加える
A[2, :] += A[1, :] * (-1)
A

array([[1, 2],
       [1, 0],
       [0, 0]])

In [113]:
# 2行目を-1倍して1行目に加える
A[0, :] += A[1, :] * (-1)
A

array([[0, 2],
       [1, 0],
       [0, 0]])

In [114]:
# 1行目を(1/2)倍する
A[0, :] = (1 / 2) * A[0, :]
A

array([[0, 1],
       [1, 0],
       [0, 0]])

In [115]:
# 1行目と2行目を入れ替える
a1 = A[0, :].copy()
a2 = A[1, :].copy()
A[0, :] = a2
A[1, :] = a1
A

array([[1, 0],
       [0, 1],
       [0, 0]])

### 2.

> 2.
> $$
\left(\begin{array}{lll}0 & 1 & 0 \\ 1 & 0 & 1 \\ 0 & 1 & 0\end{array}\right)
$$


In [27]:
import numpy as np
A = np.array([
    [0, 1, 0],
    [1, 0, 1],
    [0, 1, 0],
])

In [23]:
# 1行目を-1倍して3行目に加える
A[2, :] += (-1) * A[0, :]
A

array([[0, 1, 0],
       [1, 0, 1],
       [0, 0, 0]])

In [24]:
# 0列目を-1倍して3列目に加える
A[:, 2] += (-1) * A[:, 0]
A

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 0]])

In [25]:
# 1行目と2行目を入れ替える
a1 = A[0, :].copy()
a2 = A[1, :].copy()
A[0, :] = a2
A[1, :] = a1
A

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 0]])

### 3.

> 3.
> $$
\left(\begin{array}{lll}a & 1 & 1 \\ 1 & a & 1 \\ 1 & 1 & a\end{array}\right)
$$


わからなかった

In [199]:
from sympy import Symbol, Matrix

a = Symbol("a")
A = Matrix([
    [a, 1, 1],
    [1, a, 1],
    [1, 1, a],
])
A

Matrix([
[a, 1, 1],
[1, a, 1],
[1, 1, a]])

In [215]:
# 1行目と2行目を入れ替える
a1 = A[0, :].copy()
a2 = A[1, :].copy()
A[0, :] = a2
A[1, :] = a1
A

Matrix([
[1, a, 1],
[a, 1, 1],
[1, 1, a]])

In [216]:
A[1, :] += -a * A[0, :]
A

Matrix([
[1,        a,     1],
[0, 1 - a**2, 1 - a],
[1,        1,     a]])

In [217]:
A[2, :] += -1 * A[0, :]
A

Matrix([
[1,        a,     1],
[0, 1 - a**2, 1 - a],
[0,    1 - a, a - 1]])

In [217]:
A[2, :] += -1 * A[0, :]
A

Matrix([
[1,        a,     1],
[0, 1 - a**2, 1 - a],
[0,    1 - a, a - 1]])

未知の変数があって最終的なランクが変わりうる → 場合分けする


もし$a=1$なら

$$
\begin{pmatrix}
1 & a & 1\\
0 & 1 - a^{2} & 1 - a\\
0 & 1 - a & a - 1
\end{pmatrix}
=
\begin{pmatrix}
1 & 1 & 1\\
0 & 1 - 1^{2} & 1 - 1\\
0 & 1 - 1 & 1 - 1
\end{pmatrix}
=
\begin{pmatrix}
1 & 1 & 1\\
0 & 0 & 0\\
0 & 0 & 0
\end{pmatrix}
$$


列基本変形（列で引き算）して

$$
\begin{pmatrix}
1 & 0 & 0\\
0 & 0 & 0\\
0 & 0 & 0
\end{pmatrix}
$$

→ rank=1

もし$a \neq 1$なら

$$
\begin{pmatrix}
1 & a & 1\\
0 & 1 - a^{2} & 1 - a\\
0 & 1 - a & a - 1
\end{pmatrix}
$$

In [213]:
A[2, :] += -((1-a)/(1-a**2)) * A[1, :]
A

Matrix([
[1,        a,                             1],
[0, 1 - a**2,                         1 - a],
[0,        0, a - (1 - a)**2/(1 - a**2) - 1]])

In [196]:
A[2, :] = (1+a)/((-1+a)*(2+a)) * A[2, :]
A

Matrix([
[1,        a,                                                         1],
[0, 1 - a**2,                                                     1 - a],
[0,        0, (a + 1)*(a - (1 - a)**2/(1 - a**2) - 1)/((a - 1)*(a + 2))]])

[掃き出し法計算機 - Wolfram|Alpha](https://ja.wolframalpha.com/input?i=%E6%8E%83%E3%81%8D%E5%87%BA%E3%81%97%E6%B3%95%E8%A8%88%E7%AE%97%E6%A9%9F&assumption=%7B%22F%22%2C+%22ReducedRowEchelon%22%2C+%22theMatrix%22%7D+-%3E%22%7B%7Ba%2C+1%2C+1%7D%2C+%7B1%2C+a%2C+1%7D%2C+%7B1%2C+1%2C+a%7D%7D%22)

## 4.2

> 次の問に答えよ。
> 1. 2次の正方行列に対する階数標準形をすべて書け

$$
\begin{pmatrix}
0 & 0 \\
0 & 0 \\
\end{pmatrix}
= O_2
, \hspace{1em}
\begin{pmatrix}
1 & 0 \\
0 & 0 \\
\end{pmatrix}
, \hspace{1em}
\begin{pmatrix}
1 & 0 \\
0 & 1 \\
\end{pmatrix}
= E_2
$$

> 2. 2次の正方行列に対する階段行列をすべて書け。なお、任意の数は*を用いて表せ。

$* = 0$の状況も考えて1とおくと

$$
\begin{pmatrix}
0 & 0 \\
0 & 0 \\
\end{pmatrix}
, \hspace{1em}
\begin{pmatrix}
1 & * \\
0 & 0 \\
\end{pmatrix}
, \hspace{1em}
\begin{pmatrix}
1 & *\\
0 & 1 \\
\end{pmatrix}
$$

零行列が含まれるのかわからなかった