# 練習問題 メモ 4

## 4.1

> 次の１～３の行列の階数標準形および階数(rank)を求めよ
> 
> 1. $\left(\begin{array}{ll}1 & 2 \\ 3 & 4 \\ 5 & 6\end{array}\right)$


行ベクトルを

$$
\begin{pmatrix}
a_1 \\
a_2 \\
a_3
\end{pmatrix}
$$

とする

1. $a_2' = a_2 + (-2) \times a_1$

In [11]:
import numpy as np
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
])

In [12]:
# 1行目を-2倍して2行目に加える
A[1, :] += A[0, :] * (-2)
A

array([[1, 2],
       [1, 0],
       [5, 6]])

In [13]:
# 2行目を-1倍して1行目に加える
A[0, :] += A[1, :] * (-1)
A

array([[0, 2],
       [1, 0],
       [5, 6]])

In [14]:
# 1行目を-3倍して3行目に加える
A[2, :] += A[0, :] * (-3)
A

array([[0, 2],
       [1, 0],
       [5, 0]])

In [14]:
# 1行目を-3倍して3行目に加える
A[2, :] += A[0, :] * (-3)
A

array([[0, 2],
       [1, 0],
       [5, 0]])

In [15]:
# 2行目を-5倍して3行目に加える
A[2, :] += A[1, :] * (-5)
A

array([[0, 2],
       [1, 0],
       [0, 0]])

In [19]:
# 1行目を(1/2)倍する
A[0, :] = (1 / 2) * A[0, :]
A

array([[0, 1],
       [1, 0],
       [0, 0]])

In [20]:
# 1行目と2行目を入れ替える
a1 = A[0, :].copy()
a2 = A[1, :].copy()
A[0, :] = a2
A[1, :] = a1
A

array([[1, 0],
       [0, 1],
       [0, 0]])

> 2. $\left(\begin{array}{lll}0 & 1 & 0 \\ 1 & 0 & 1 \\ 0 & 1 & 0\end{array}\right)$


In [27]:
import numpy as np
A = np.array([
    [0, 1, 0],
    [1, 0, 1],
    [0, 1, 0],
])

In [23]:
# 1行目を-1倍して3行目に加える
A[2, :] += (-1) * A[0, :]
A

array([[0, 1, 0],
       [1, 0, 1],
       [0, 0, 0]])

In [24]:
# 0列目を-1倍して3列目に加える
A[:, 2] += (-1) * A[:, 0]
A

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 0]])

In [25]:
# 1行目と2行目を入れ替える
a1 = A[0, :].copy()
a2 = A[1, :].copy()
A[0, :] = a2
A[1, :] = a1
A

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 0]])

> 3. $\left(\begin{array}{lll}a & 1 & 1 \\ 1 & a & 1 \\ 1 & 1 & a\end{array}\right)$


In [87]:
#TODO: 

In [85]:
from sympy import Symbol, Matrix

a = Symbol("a")
A = Matrix([
    [a, 1, 1],
    [1, a, 1],
    [1, 1, a],
])
A

Matrix([
[a, 1, 1],
[1, a, 1],
[1, 1, a]])

In [86]:
A[0, :] += -1 * A[1, :]
A[1, :] += 1 * A[0, :]
A

Matrix([
[a - 1, 1 - a, 0],
[    a,     1, 1],
[    1,     1, a]])

In [82]:
A[0, :] += -1 * A[1, :]
A[1, :] += 1 * A[0, :]
A[:, 0] += 1 * A[:, 1]
A

Matrix([
[    0, 1 - a, 0],
[a + 1,     1, 1],
[    2,     1, a]])

In [48]:
A[0, :] += -1 * A[1, :]
A[:, 0] += -1 * A[:, 2]
A

Matrix([
[a - 1, 1 - a, 0],
[    0,     a, 1],
[1 - a,     1, a]])

In [43]:
A[1, :] += -1 * A[0, :]
A[1, :] += -1 * A[2, :]
A

Matrix([
[ a,     1,  1],
[-a, a - 2, -a],
[ 1,     1,  a]])

## 4.2

> 次の問に答えよ。
> 1. 2次の正方行列に対する階数標準形をすべて書け

$$
\begin{pmatrix}
0 & 0 \\
0 & 0 \\
\end{pmatrix}
= O_2
, \hspace{1em}
\begin{pmatrix}
1 & 0 \\
0 & 0 \\
\end{pmatrix}
, \hspace{1em}
\begin{pmatrix}
1 & 0 \\
0 & 1 \\
\end{pmatrix}
= E_2
$$

> 2. 2次の正方行列に対する階段行列をすべて書け。なお、任意の数は*を用いて表せ。

$$
\begin{pmatrix}
0 & 0 \\
0 & 0 \\
\end{pmatrix}
= O_2
, \hspace{1em}
\begin{pmatrix}
* & * \\
0 & 0 \\
\end{pmatrix}
, \hspace{1em}
\begin{pmatrix}
* & *\\
0 & * \\
\end{pmatrix}
= E_2
$$