# 練習問題メモ 5（連立1次方程式）

## 5.1

> 掃き出し法により、次の1～3の連立1次方程式を解け。また、係数行列および拡大係数行列について、それぞれの階数を求めよ

> 1. 
$$
\left(\begin{array}{ll}
1 & 2 \\
3 & 4 \\
5 & 6
\end{array}\right)\left(\begin{array}{l}
x_1 \\
x_2
\end{array}\right)=\left(\begin{array}{l}
1 \\
0 \\
0
\end{array}\right)
$$

In [209]:
import numpy as np
A = np.array([
    [1, 2, 1],
    [3, 4, 0],
    [5, 6, 0],
], dtype=np.float16)

In [210]:
# 1行目を-2倍して2行目に加える
A[1, :] += A[0, :] * (-2)
A

array([[ 1.,  2.,  1.],
       [ 1.,  0., -2.],
       [ 5.,  6.,  0.]], dtype=float16)

In [211]:
# 1行目を-3倍して3行目に加える
A[2, :] += A[0, :] * (-3)
A

array([[ 1.,  2.,  1.],
       [ 1.,  0., -2.],
       [ 2.,  0., -3.]], dtype=float16)

In [212]:
# 3行目を(1/2)倍する
A[2, :] = (1 / 2) * A[2, :]
A

array([[ 1. ,  2. ,  1. ],
       [ 1. ,  0. , -2. ],
       [ 1. ,  0. , -1.5]], dtype=float16)

In [213]:
# 2行目を-1倍して3行目に加える
A[2, :] += A[1, :] * (-1)
A

array([[ 1. ,  2. ,  1. ],
       [ 1. ,  0. , -2. ],
       [ 0. ,  0. ,  0.5]], dtype=float16)

In [214]:
# 2行目を-1倍して1行目に加える
A[0, :] += A[1, :] * (-1)
A

array([[ 0. ,  2. ,  3. ],
       [ 1. ,  0. , -2. ],
       [ 0. ,  0. ,  0.5]], dtype=float16)

In [215]:
# 1行目を(1/2)倍する
A[0, :] = (1 / 2) * A[0, :]
A

array([[ 0. ,  1. ,  1.5],
       [ 1. ,  0. , -2. ],
       [ 0. ,  0. ,  0.5]], dtype=float16)

In [216]:
a1 = A[1, :].copy()
a2 = A[2, :].copy()
A[1, :] = a2
A[2, :] = a1
A

array([[ 1,  1, -2,  0],
       [ 0,  0,  0,  0],
       [ 0,  1, -1, -1]])

$$
\left(\begin{array}{cc|c}
1 & 0 & -2\\
0 & 1 & 3/2 \\
0 & 0 & 1/2
\end{array}\right)
$$

In [217]:
# 検算
import numpy as np
A = np.array([
    [1, 2],
    [3, 4],
])
x = np.array([1, 0])
np.linalg.solve(A, x)

array([-2. ,  1.5])

In [218]:
# 検算
import numpy as np
A = np.array([
    [3, 4],
    [5, 6],
])
x = np.array([1, 0])
np.linalg.solve(A, x)

array([-3. ,  2.5])

> 1-2. 係数行列の階数

$$
\begin{pmatrix}
1 & 0\\
0 & 1\\
0 & 0\\
\end{pmatrix}
$$

と、階段行列の形であり零の行ベクトルでない行数は2なので2


> 1-3. 拡大係数行列の階数

3


> 2.
> $$
\left(\begin{array}{ccc}
1 & 1 & -2 \\
1 & -2 & 1 \\
-2 & 1 & 1
\end{array}\right)\left(\begin{array}{l}
x_1 \\
x_2 \\
x_3
\end{array}\right)=\left(\begin{array}{c}
0 \\
3 \\
-3
\end{array}\right)
$$

In [154]:
import numpy as np
A = np.array([
    [1, 1, -2, 0],
    [1, -2, 1, 3],
    [-2, 1, 1, -3],
])

In [155]:
A[1, :] += A[0, :] * (-1)
A

array([[ 1,  1, -2,  0],
       [ 0, -3,  3,  3],
       [-2,  1,  1, -3]])

In [156]:
A[2, :] += A[0, :] * (2)
A

array([[ 1,  1, -2,  0],
       [ 0, -3,  3,  3],
       [ 0,  3, -3, -3]])

In [157]:
A[2, :] += A[1, :] * (1)
A

array([[ 1,  1, -2,  0],
       [ 0, -3,  3,  3],
       [ 0,  0,  0,  0]])

In [158]:
A[1, :] = A[1, :] * (-1/3)
A

array([[ 1,  1, -2,  0],
       [ 0,  1, -1, -1],
       [ 0,  0,  0,  0]])

In [159]:
A[0, :] += A[1, :] * (-1)
A

array([[ 1,  0, -1,  1],
       [ 0,  1, -1, -1],
       [ 0,  0,  0,  0]])

In [181]:
# # 検算
# import numpy as np
# A = np.array([
#     [1, 1, -2],
#     [1, -2, 1],
#     [-2, 1, 1],
# ])
# x = np.array([0, 3, -3])
# np.linalg.solve(A, x)

→ $x_1 = 1, x_2 = -1$

$x_3$は…？

> 3.
$$
\left(\begin{array}{llll}
1 & 2 & 3 & 4 \\
2 & 3 & 4 & 1 \\
0 & 1 & 2 & 7
\end{array}\right)\left(\begin{array}{l}
x_1 \\
x_2 \\
x_3 \\
x_4
\end{array}\right)=\left(\begin{array}{l}
1 \\
0 \\
1
\end{array}\right)
$$

In [186]:
A = np.array([
    [1, 2, 3, 4, 1],
    [2, 3, 4, 1, 0],
    [0, 1, 2, 7, 1],
])
np.linalg.matrix_rank(A)
np.linalg.matrix_rank(A[:, :3])

2

In [196]:
from sympy import Matrix
A = Matrix([
    [1, 2, 3, 4, 1],
    [2, 3, 4, 1, 0],
    [0, 1, 2, 7, 1],
])

In [197]:
A[1, :] += A[0, :] * (-2)
A

Matrix([
[1,  2,  3,  4,  1],
[0, -1, -2, -7, -2],
[0,  1,  2,  7,  1]])

In [198]:
A[2, :] += A[1, :]
A

Matrix([
[1,  2,  3,  4,  1],
[0, -1, -2, -7, -2],
[0,  0,  0,  0, -1]])

In [199]:
A[1, :] = A[1, :] * (-1)
A

Matrix([
[1, 2, 3, 4,  1],
[0, 1, 2, 7,  2],
[0, 0, 0, 0, -1]])

In [200]:
A[0, :] += A[1, :] * (-2)
A

Matrix([
[1, 0, -1, -10, -3],
[0, 1,  2,   7,  2],
[0, 0,  0,   0, -1]])

In [174]:
from sympy import Matrix
A = Matrix([
    [1, 2, 3, 4, 1],
    [2, 3, 4, 1, 0],
    [0, 1, 2, 7, 1],
])

In [175]:
A[1, :] += A[0, :] * (-2)
A

Matrix([
[1,  2,  3,  4,  1],
[0, -1, -2, -7, -2],
[0,  1,  2,  7,  1]])

## 5.2

> 掃き出し法により、次の同次連立 1 次方程式を解け。
> $$
\left(\begin{array}{llll}
1 & 2 & 3 & 4 \\
2 & 3 & 4 & 1 \\
0 & 1 & 2 & 7
\end{array}\right)\left(\begin{array}{l}
x_1 \\
x_2 \\
x_3 \\
x_4
\end{array}\right)=\left(\begin{array}{l}
0 \\
0 \\
0
\end{array}\right)
$$

In [202]:
from sympy import Matrix
A = Matrix([
    [1, 2, 3, 4, 0],
    [2, 3, 4, 1, 0],
    [0, 1, 2, 7, 0],
])

In [204]:
A = np.array([
    [1, 2, 3, 4, 0],
    [2, 3, 4, 1, 0],
    [0, 1, 2, 7, 0],
])
np.linalg.matrix_rank(A)

2

In [205]:
np.linalg.solve(A[:, :3], A[:, -1])

LinAlgError: Singular matrix

## 5.3

> p,q,rを定数とする。連立1次方程式
> $$
\left(\begin{array}{ccc}
-2 & 1 & 1 \\
1 & -2 & 1 \\
1 & 1 & -2
\end{array}\right)\left(\begin{array}{l}
x_1 \\
x_2 \\
x_3
\end{array}\right)=\left(\begin{array}{l}
p \\
q \\
r
\end{array}\right)
$$
> の解が存在するためのp,q,rの条件を求めよ。

検算用
- [掃き出し法計算機 - Wolfram|Alpha](https://ja.wolframalpha.com/input?i=%E6%8E%83%E3%81%8D%E5%87%BA%E3%81%97%E6%B3%95%E8%A8%88%E7%AE%97%E6%A9%9F)