# 練習問題メモ 6（正則行列）

## 6.1

> 次の問いに答えよ。
>
> 1.正則行列の定義を書け。

$n$次正方行列$A$に対し

$$
A^{-1}A = AA^{-1} = I
$$

を満たす正方行列$A^{-1}$が存在する行列$A$を正則行列という


また、正則行列であるための必要十分条件は$\operatorname{det}(A) \neq 0$である

> 2.次の(ア)、(イ)の正則行列の逆行列を求めよ。
> $$
\text { (ア) }\left(\begin{array}{lll}
1 & a & b \\
0 & 1 & c \\
0 & 0 & 1
\end{array}\right) \quad \text { (イ) }\left(\begin{array}{lll}
1 & 1 & 1 \\
1 & 1 & 2 \\
1 & 2 & 1
\end{array}\right)
$$

### 2. (ア)

$$
A = \left(\begin{array}{lll}
1 & a & b \\
0 & 1 & c \\
0 & 0 & 1
\end{array}\right)
$$

とおくと、

$$
A^{-1} = \frac{1}{|A|} \tilde{A}
$$

（$\tilde{A}$は余因子行列）

なので、行列式と余因子行列を求めていく。

まず行列式は

$$
|A| = 1^3 + a \cdot c \cdot 0 + 0 \cdot 0 \cdot b
    - 1 \cdot c \cdot 0 - a \cdot 0 \cdot 1 - b \cdot 1 \cdot 0\\
    = 1
$$

なので

$$
A^{-1} = \frac{1}{1} \tilde{A}
\to A^{-1} = \tilde{A}
$$

であることがわかる

余因子行列は

$$
\begin{align}
\tilde{A_{11}} &= (-1)^{1+1} |A_{11}| = 1 \times 1 = 1\\
\tilde{A_{12}} &= (-1)^{1+2} |A_{12}| = -1 \times 0 = 0\\
\tilde{A_{13}} &= (-1)^{1+3} |A_{13}| = 1 \times 0 = 0\\
\tilde{A_{21}} &= (-1)^{2+1} |A_{21}| = -1 \times a = -a\\
\tilde{A_{22}} &= (-1)^{2+2} |A_{22}| = 1 \times 1 = 1\\
\tilde{A_{23}} &= (-1)^{2+3} |A_{23}| = -1 \times 0 = 0\\
\tilde{A_{31}} &= (-1)^{3+1} |A_{31}| = 1 \times (ac-b) = ac-b\\
\tilde{A_{32}} &= (-1)^{3+2} |A_{32}| = -1 \times c = -c\\
\tilde{A_{33}} &= (-1)^{3+3} |A_{33}| = 1 \times 1 = 1\\
\end{align}
$$

$$
\tilde{A} =
\begin{pmatrix}
1 & 0 & 0\\
-a & 1 & 0\\
ac-b & -c & 1
\end{pmatrix}
= A^{-1}
$$

$$
A^{-1} A =
\begin{pmatrix}
1 & 0 & 0\\
-a & 1 & 0\\
ac-b & -c & 1
\end{pmatrix}
\begin{pmatrix}
1 & a & b \\
0 & 1 & c \\
0 & 0 & 1
\end{pmatrix}
=
\begin{pmatrix}
1 & a & b \\
-a & -a^2+1 & -ab+c \\
ac-b & a^c-ab -c & abc-b^2 - c^2 + 1
\end{pmatrix}
$$

きちんと逆行列が計算できているならこの積は単位行列になるはずなので、$a,b,c$はすべてゼロのはず

よって

$$
A^{-1} = 
\begin{pmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{pmatrix}
$$

### 2. (イ)

$$
A = 
\left(\begin{array}{lll}
1 & 1 & 1 \\
1 & 1 & 2 \\
1 & 2 & 1
\end{array}\right)
$$

とおく。

$$
|A| = 1^3 + 1^2 \times 2 + 1^2 \times 2
    - 1 \times 2^2 - 1^3 - 1^3\\
    = 1 + 2 + 2 - 4 - 1 - 1\\
    = -1
$$

$$
\begin{align}
\tilde{A}_{11} = (-1)^{1+1} |A_{11}| = 1 \times (1^2 - 2^2) = -3\\
\tilde{A}_{12} = (-1)^{1+2} |A_{12}| = -1 \times (1 - 2) = 1\\
\tilde{A}_{13} = (-1)^{1+3} |A_{13}| = 1 \times (2 - 1) = 1\\
\tilde{A}_{21} = (-1)^{2+1} |A_{21}| = -1 \times (1 - 2) = 1\\
\tilde{A}_{22} = (-1)^{2+2} |A_{22}| = 1 \times (1 - 1) = 0\\
\tilde{A}_{23} = (-1)^{2+3} |A_{23}| = -1 \times (2 - 1) = -1\\
\tilde{A}_{31} = (-1)^{3+1} |A_{31}| = 1 \times (2 - 1) = 1\\
\tilde{A}_{32} = (-1)^{3+2} |A_{32}| = -1 \times (2 - 1) = -1\\
\tilde{A}_{33} = (-1)^{3+3} |A_{33}| = 1 \times (1 - 1) = 0\\
\end{align}
$$

$$
\tilde{A} = \begin{pmatrix}
-3 & 1 & 1\\
1 & 0 & -1\\
1 & -1 & 0
\end{pmatrix}
$$

$$
A^{-1} = \frac{1}{|A|} \tilde{A}
= - \tilde{A}
= \begin{pmatrix}
3 & -1 & -1\\
-1 & 0 & 1\\
-1 & 1 & 0
\end{pmatrix}
$$

In [31]:
import numpy as np

A = np.array([
    [1, 1, 1],
    [1, 1, 2],
    [1, 2, 1],
])

def cofactor(A, i, j):
    """余因子を計算する関数"""
    A_minor = np.delete(A, i, axis=0)
    A_minor = np.delete(A_minor, j, axis=1)
    return (-1)**(i + j) * np.linalg.det(A_minor)

def cofactor_matrix(A):
    C = np.zeros_like(A, dtype=np.float16)
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            C[i, j] = cofactor(A, i=i, j=j)
    return C.T

-cofactor_matrix(A)

array([[ 3., -1., -1.],
       [-1., -0.,  1.],
       [-1.,  1., -0.]], dtype=float16)

In [32]:
np.linalg.inv(A)

array([[ 3., -1., -1.],
       [-1.,  0.,  1.],
       [-1.,  1.,  0.]])

In [33]:
np.linalg.det(A[1:,1:])

-2.9999999999999996

## 6.2

> $n$ 次の正方行列 $A_{11}, A_{12}, A_{22}, X_{11}, X_{12}, X_{21}, X_{22}$ を用いて、 $2 n$ 次の正方行列 $A$ および $X$ を
> $$
A=\left(\begin{array}{cc}
A_{11} & A_{12} \\
O & A_{22}
\end{array}\right), X=\left(\begin{array}{ll}
X_{11} & X_{12} \\
X_{21} & X_{22}
\end{array}\right)
$$
>
> により定める。
> 1. 積 $A X$ を計算せよ。
> 2. $A_{11}$ および $A_{22}$ がともに正則ならば、 $A$ は正則であることを示し、さらに $A$ の逆行列を求めよ。

> 1. 積 $A X$ を計算せよ。

$$
AX = 
\begin{pmatrix}
A_{11} X_{11} + A_{12} X_{21} & A_{11} X_{12} + A_{12} X_{22}\\
A_{22} X_{21} & A_{22} X_{22}
\end{pmatrix}
$$

> 2. $A_{11}$ および $A_{22}$ がともに正則ならば、 $A$ は正則であることを示し

$$
|A|
= |A_{11}| \cdot |A_{22} - O A_{11}^{-1} A_{12}|
= |A_{11}| \cdot |A_{22}|
$$

よって

$$
|A_{11}| \neq 0 
\land
|A_{22}| \neq 0
\implies
|A| \neq 0
$$


>  $A$ の逆行列を求めよ。

$$
A^{-1} = 
\begin{pmatrix}
A_{11}^{-1} + A_{11}^{-1} A_{12} A_{22}^{-1} O A_{11}^{-1}
& -A_{11}^{-1} A_{12} A_{22}^{-1}\\
-A_{22}^{-1} O A_{11}^{-1}
& A_{22}^{-1}
\end{pmatrix}
=
\begin{pmatrix}
A_{11}^{-1} & -A_{11}^{-1} A_{12} A_{22}^{-1}\\
O & A_{22}^{-1}
\end{pmatrix}
$$

## 6.3

> 次の問いに答えよ。
> 1. $A$ を $n$ 次の正方行列とする。自然数 $m$ に対して、
> $$
\left(E_n-A\right)\left(E_n + A+A^2+\cdots+A^{m-1}\right)
$$
>
> を計算せよ。
>
> 2. べき零行列の定義を書け。
> 3. $A$ が $n$ 次のべき零行列ならば、 $E_n-A$ は正則であることを示せ。

> 1. $A$ を $n$ 次の正方行列とする。自然数 $m$ に対して、
> $$
\left(E_n-A\right)\left(E_n+A+A^2+\cdots+A^{m-1}\right)
$$
>
> を計算せよ。

行列もスカラーと同様に分配法則があるので

$$
\begin{align}
(E_n - A)(E_n+A+A^2+\cdots+A^{m-1})
&= 
E_n + A + A^2 + \cdots + A^{m-1}
- (A + A^2 + \cdots + A^{m})\\
&= E_n - A^{m}
\end{align}
$$

> 2. べき零行列の定義を書け。

$n$次正方行列$A$について、

$$
A^k = O
$$

となる自然数$k$が存在する行列

> 3. $A$ が $n$ 次のべき零行列ならば、 $E_n-A$ は正則であることを示せ。


https://mathlandscape.com/nilpotent-matrix/ の性質2によれば、べき零行列$A$に対する固有方程式は

$$
|\lambda E_n - A| = \lambda^n
$$

になるので（なんで？）、$\lambda=1$なら

$$
|E_n - A| = 1
$$

なので$E_n - A$は正則

:::{card}
べき零行列の性質

1. べき零行列は正則ではない
    - $AB=I$の両辺を$k$乗したとき$A^k B^k = I^k \to O B^k = I$となり$O=I$は矛盾するため
    - $A^k = O$のとき$|A^k| = |A|^k = 0 \to |A|=0$
2. べき零行列は固有値がゼロ
    - $A^k x = \lambda^k x$、$A^k = O \to \lambda^k=0 \to \lambda = 0$
3. べき零行列のトレースは0
    - 固有値の和はトレースと一致する
    - トレースは対角成分の和 → べき零行列は対角成分が0
4. $\lambda I - A(\lambda \neq 0)$が正則
    - $|\lambda I_n - A^k| = \lambda^n$
    - $|\lambda I_n - A^k| \neq 0 \operatorname{if} \lambda \neq 0$
:::

In [42]:
# 例
import numpy as np
A = np.array([
    [0, 1, 2],
    [0, 0, 1],
    [0, 0, 0],
])

A @ A @ A

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [50]:
I = np.eye(3)
print(I - A)
np.linalg.det(I - A)

[[ 1. -1. -2.]
 [ 0.  1. -1.]
 [ 0.  0.  1.]]


1.0

In [43]:
np.linalg.det(A)

0.0

## 参考

- [ブロック行列の行列式，逆行列の公式と証明 | 高校数学の美しい物語](https://manabitimes.jp/math/1203#5)
- [べき零行列の定義・例・性質7つとその証明 | 数学の景色](https://mathlandscape.com/nilpotent-matrix/)
- [べきゼロ行列とは：例、指数行列、性質 | 趣味の大学数学](https://math-fun.net/20210607/14883/)